name: "flw 的工具箱"
baseurl: ""
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
# defaults:
#     - scope:
#         path: ""
#         type: page
#       values:
#         layout: site
#     - scope:
#         path: ""
#         type: post
#       values:
#         layout: article
